global:
  environment: ""
  logLevel: debug
  dbName: myProductApp
  cartMicrosvcsMapping: mycart

image:
   express: ""
   mongo: mongo:latest

services:
  express:
    name: product-express-app
    type: ClusterIP
    port: 8081
  mongo:
    name: product-mongo-db
    type: ClusterIP
    port: 27017
  gateway:
    name: gateway-express-app
    port: 8081


app:
 express:
   port: 8091
 mongo:
   port: 27017
 

config:
  name: product-app-config

